### ISSUE TITLE
getNumberOfEdges returns 0

### ISSUE THREAD

**Issue by pletzer** [pletzer/mint#68]
I’ve been trying to check so far is whether you can get the same kind of grids by loading as by creating in memory with setPoints. One thing I’ve noticed is that when I try the getNumberOfEdges method, it returns 0 for grids made with setPoints but seems to work correctly for loaded grids. This can be demonstrated by including the line `print(gr.getNumberOfEdges())` in test_grid.test_create_grid. Is this a bug or is there some additional information I need to provide the Grid object that I’m missing? The methods getNodeIds and getEdgeId also seem to fail in this case.

**Comment by pletzer** [comment]
Thanks for reporting. 

When loading the grid from NetCDF, the format is assumed to be of UGRID type with independent IDs for cells, edges and vertices. Internally the grid is stored as a collection of 2D cells (quads). In the later case, the ID of each edge is determined by each cell having four edges ordered in counterclockwise direction. In this case the number of edges is just the number of cells * 4.

Method getNumberOfEdges refers to the number of unique edge IDs from the ugrid file. When creating the grid in memory with setPoints, the ugrid mesh is never created and therefore the number of edges returned is zero.

I agree this causes confusion but I don't have a quick solution, I would need to think about this...

**Comment by stephenworsley** [comment]
This seems like it would work. Would this be as a replacement for `setPoints`? Also, I imagine face2node and face2edge could be optional (e.g. in the case where the UGRID mesh is topologically 2D), is that likely to be the case here also?

**Comment by pletzer** [comment]
Thanks @stephenworsley . I'm thinking of keeping setPoints but keeping it clear that this will set the points on cell per cell basis, which is the underlying way to store a mesh in MINT.

**Comment by pletzer** [comment]
@stephenworsley : When you say topological 2D, do you mean structured grid? Structured grids don't need any connectivity as it is implied. Every unstructured grid needs the connectivity. If UGrid requires the connectivity then it should be a compulsory argument. On the other hand one could also have a `setStructuredGrid(self, lons, lats)` method in addition (?)

**Comment by stephenworsley** [comment]
@pletzer: Ah, I think I mean topologically 1D, in the sense that the UGRID `topology_dimension` is 1 and there is only edge_node_conectivity

**Comment by pletzer** [comment]
RegridEdges now has setSrcGrid and setDstGrid methods
